### ISSUE TITLE
Autocomplete for @each based classes

### ISSUE THREAD

**Issue by rolandgnm** [robinbentley/vscode-sass-indented#57]
Hey guys, I was wondering if/how can I get full intellisense for classes created programatically, e.g. using `@each`, as follows: 
```scss
@each $prop in $properties {
  @each $size, $length in $spacers {
    .#{$prop}#{$size} {
      #{$prop}: $length !important;
    }
    .#{$prop}-top#{$size},
    .#{$prop}-y#{$size} {
      #{$prop}-top: $length !important;
    }
    .#{$prop}-right#{$size},
    .#{$prop}-x#{$size} {
      #{$prop}-right: $length !important;
    }
    .#{$prop}-bottom#{$size},
    .#{$prop}-y#{$size} {
      #{$prop}-bottom: $length !important;
    }
    .#{$prop}-left#{$size},
    .#{$prop}-x#{$size} {
      #{$prop}-left: $length !important;
    }
  }
}

.margin-auto {
  margin: auto !important;
}

.margin-top-auto,
.margin-y-auto {
  margin-top: auto !important;
}

.margin-right-auto,
.margin-x-auto {
  margin-right: auto !important;
}

.margin-bottom-auto,
.margin-y-auto {
  margin-bottom: auto !important;
}
.margin-left-auto,
.margin-x-auto {
  margin-left: auto !important;
}
```

When I try to get intellisense for these classes I only the statically declared ones, like any `*-auto` classes. 

Thanks in advance!
